DROP DATABASE IF EXISTS DEV_BIG_PRODE;
CREATE DATABASE database2_links CHARSET utf8mb4;
USE DEV_BIG_PRODE;

-- USERS TABLE
CREATE TABLE users(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);